name: rochelleredfield
favicon: null
layout_spectrum: 0.499936020700261
typography_spectrum: 0.6726370898541063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5244605471380055
  lightness: 0.1959462205413729
  saturation: 0.9084228083956987
  rhythmicContrast: 0.8078661388717592
purpose: []
